name: Firebase Deploy
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Make Public Dir
        run: |
          mkdir public
          cp ./*.html public/
          cp ./*.css public/
          cp -r css public/
          cp -r images public/
          cp -r js public/
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}